name: Build for macOS Intel (amd64)

on:
  workflow_dispatch:  # manual trigger

jobs:
  build:
    name: Build for macOS Intel (amd64)
    runs-on: macos-12

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Install Wails CLI
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Build Wails Application
      env:
        CGO_ENABLED: 1
        GOOS: darwin
        GOARCH: amd64
      run: wails build
      working-directory: code

    - name: Archive Build Output
      uses: actions/upload-artifact@v4
      with:
        name: wails-macos-amd64
        path: code/build/bin/
